DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS directors;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL, 
  password TEXT NOT NULL
);

CREATE TABLE review (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  movie_id INTEGER FOREIGN KEY NOT NULL,
  author_id INTEGER FOREIGN KEY NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  star TINYINT UNSIGNED,
  FOREIGN KEY (movie_id) REFERENCES movies(id),
  FOREIGN KEY (author_id) REFERENCES user(id)
);

CREATE TABLE movies (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  movie_name VARCHAR(100) NOT NULL,
  year_rel SMALLINT,
  runtime TINYINT,
  genres TEXT,
  director_id INTEGER FOREIGN KEY NOT NULL,
  FOREIGN KEY (director_id) REFERENCES directors(id)
);

CREATE TABLE directors (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  director_name VARCHAR(40) NOT NULL,
  birth_year TINYINT,
  well_known_titles VARCHAR(100)
);